benzhu_system/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from benzhu_system.apps.service.views import service, service_list, service_detail, company_detail, service_comment, \
    service_favourite
from benzhu_system.apps.community.views import community_index, notice_detail, community_detail, feedback, \
    feedback_detail
from benzhu_system.apps.base.views import index
from benzhu_system.core.page.views import page
from benzhu_system.apps.account.views import login, logout, register, user_center, user_settings, myfeedback, \
    myfeedback_detail, myservice, user_info, user_password, get_user_info
from benzhu_system.apps.comment.views import comment_posted
from benzhu_system.apps.atom.article.views import get_unread_message


urlpatterns = patterns('',

    url(r'^$', index),
    url(r'^page/(\d+)/$', page),

    url(r'^community/$', community_index),
    url(r'^community/notice/(\d+)$', notice_detail),
    url(r'^community/introduction/$', community_detail),
    url(r'^community/feedback/$', feedback),
    url(r'^community/feedback/(\d+)$', feedback_detail),

    url(r'^service/$', service),
    url(r'^service/(\d+)/$', service_list),
    url(r'^service/\d+/(\d+)/$', service_detail),
    url(r'^company/(\d+)/$', company_detail),
    url(r'^service/\d+/(\d+)/comment$', service_comment),
    url(r'^service/favourite$', service_favourite),

    url(r'^user_login/$', login),
    url(r'^user_logout/$', logout),
    url(r'^get_user_info$', get_user_info),
    url(r'^register/$', register),
    url(r'^user_center/$', user_center),
    url(r'^settings/$', user_settings),
    url(r'^myfeedback/$', myfeedback),
    url(r'^myfeedback/(\d+)$', myfeedback_detail),
    url(r'^myservice/$', myservice),
    url(r'^user_info/$', user_info),
    url(r'^user_password/$', user_password),

    url(r'^admin/article/feedback/count', get_unread_message),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^comments/posted/$', comment_posted),
    url(r'^comments/', include('django.contrib.comments.urls')),
)

# Append
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

benzhu_system/core/atom/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from benzhu_system.core.gallery.models import GalleryManagement
from datetime import datetime


class Atom(models.Model):
    name = models.CharField(max_length=150)
    gallery = models.ForeignKey(GalleryManagement, null=True, blank=True)
    info = RichTextField(default='',  null=True, blank=True)
    person = models.ManyToManyField(User, default='',  null=True, blank=True)
    time = models.DateTimeField(default=datetime.now)
    state = models.CharField(max_length=150, default='',  null=True, blank=True)
    count = models.IntegerField(default=0,  null=True, blank=True)

    class Meta:
        abstract = True

benzhu_system/apps/comment/forms.py
from django import forms
from django.contrib.comments.forms import CommentForm
from benzhu_system.apps.comment.models import StarComment

class StarCommentForm(CommentForm):
    star = forms.IntegerField()

    def get_comment_model(self):
        # Use our custom comment model instead of the built-in one.
        return StarComment

    def get_comment_create_data(self):
        # Use the data of the superclass, and add in the title field
        data = super(StarCommentForm, self).get_comment_create_data()
        data['star'] = self.cleaned_data['star']
        return data

benzhu_system/apps/service/views.py
from django.template import loader, Context
from django.http import Http404, HttpResponse, HttpResponseRedirect
from benzhu_system.apps.atom.product.models import Service
from benzhu_system.apps.atom.unit.models import Company
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.db.models import Q, Avg
from django.contrib.auth.decorators import login_required
from benzhu_system.apps.account.models import Profile
from benzhu_system.core.gallery.models import GalleryManagement
from benzhu_system.apps.comment.models import StarComment
from django.contrib.contenttypes.models import ContentType


def service(request):

    community_id = request.GET.get("community_id")
    if community_id is not None:
        request.session['community_id'] = community_id

    if request.method == 'POST':

        try:
            key = request.POST.get('key')
        except ValueError:
            raise Http404()

        posts = Service.objects.filter(Q(name__contains=key) | Q(info__contains=key))

        return render_to_response('service_list.html', {"posts": posts}, context_instance=RequestContext(request))

    gallery = GalleryManagement.objects.get(id=1)
    gallery_pic = gallery.galleryPic.all

    t = loader.get_template("service.html")
    c = Context()
    return render_to_response('service.html', {"gallery": gallery_pic}, context_instance=RequestContext(request))


def service_list(request, offset):

    if request.method == 'POST':

        try:
            key = request.POST.get('key')
        except ValueError:
            raise Http404()

        posts = Service.objects.filter(Q(name__contains=key) | Q(info__contains=key))

        return render_to_response('service_list.html', {"posts": posts}, context_instance=RequestContext(request))

    try:
        type_id = int(offset)
    except ValueError:
        raise Http404()
    
    posts = Service.objects.filter(type=type_id)
    stars = {}
    for post in posts:
        try:
            content_type = ContentType.objects.get(name='Service') 
            star_comment = StarComment.objects.filter( 
                    Q( object_pk = post.pk ) & 
                    Q( content_type = content_type.id ) 
            )
            stars[post.pk] = star_comment.aggregate(Avg('star')).get('star__avg')
        except:
            stars[post.pk] = 0

    return render_to_response('service_list.html', {"posts": posts, "stars": stars}, context_instance=RequestContext(request))


def service_detail(request, offset):
    try:
        service_id = int(offset)
    except ValueError:
        raise Http404()
    
    posts = Service.objects.filter(id=service_id)
    service = Service.objects.get(id=service_id)
    gallery = service.gallery.galleryPic.all()

    try:
        content_type = ContentType.objects.get(name='Service') 
        star_comment = StarComment.objects.filter( 
                Q( object_pk = service.pk ) & 
                Q( content_type = content_type.id ) 
        )
        avg_star = star_comment.aggregate(Avg('star')).get('star__avg')
    except:
        avg_star = 0

    return render_to_response("service_detail.html", 
            {"posts": posts, "service": service, "ID": service_id, "gallery": gallery, "avg_star": avg_star, },
            context_instance=RequestContext(request))


def company_detail(request, offset):
    try:
        company_id = int(offset)
    except ValueError:
        raise Http404()

    company = Company.objects.get(id=company_id)

    try:
        t = loader.get_template("company_detail.html")
    except IndexError:
        raise Http404()

    c = Context({"company": company})
    return HttpResponse(t.render(c))


@login_required
def service_comment(request, offset):
    try:
        service_id = int(offset)
    except ValueError:
        raise Http404()

    service = Service.objects.get(id=service_id)

    return render_to_response("service_comment.html", {"service": service}, 
        context_instance=RequestContext(request))


@login_required
def service_favourite(request):
    try:
        service_id = request.GET.get("service_id")
    except ValueError:
        raise Http404()

    try:
        remove_sign = int(request.GET.get("remove"))
    except TypeError:
        remove_sign = None

    service = Service.objects.get(id=service_id)

    try:
        profile = Profile.objects.get(user=request.user)
        
        if not remove_sign == 1:
            profile.service.add(service)
        else:
            profile.service.remove(service)

        profile.save()

    except Profile.DoesNotExist:
        raise Http404()

    return HttpResponseRedirect("/service/")

benzhu_system/apps/service/templates/company_detail.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	    <title>benzhu_system</title>
	    <script src="/static/web/js/jquery-1.11.1.min.js"></script>
	    <link rel="stylesheet" href="/static/web/css/main.css" />
	    <link rel="stylesheet" href="/static/web/css/bootstrap.css">
	    <script>
			$(function() {
				$(".banner_left").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"white"} );
					$(".goback_button").css( {"color":"#FF4A00"} );
				});
				$(".banner_left").bind("touchend", function() {
					$(this).css( {"backgroundColor":"transparent"} );
					$(".goback_button").css( {"color":"white"} );
				});
				$(".banner_right").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"#FD9729"} );
				});
				$(".banner_right").bind("touchend", function() {
					$(this).css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
				$(".phone").bind("touchstart", function() {
					$(this).find(".tel").css( {"backgroundColor":"#D4D7DA"} );
					$(this).find(".tel_icon").css( {"backgroundColor":"#FD9729"} );
				});
				$(".phone").bind("touchend", function() {
					$(this).find(".tel").css( {"backgroundColor":"rgba(94,92,87,0.8)"} );
					$(this).find(".tel_icon").css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
				$(".phone").bind("touchmove", function() {
					$(this).find(".tel").css( {"backgroundColor":"rgba(94,92,87,0.8)"} );
					$(this).find(".tel_icon").css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
			});	
		</script>
	</head>
	<body class="apps_background">
		<div class="container-fluid service_detail">
			<div class="row">
	    		<div class="banner">
	    			<div class="banner_left col-xs-2">
	    				<a href="javascript:history.back()">
	    					<div class="goback_button">
	    						<span class="glyphicon glyphicon-arrow-left"></span>
	    					</div>
	    				</a>
					</div>	
		    		<div class="banner_middle col-xs-8">
		    			<div class="service_name">
		    				{{company.name}}
		    			</div>
		    		</div>
		    		<div class="banner_right col-xs-2">
		    			<a href="tel:{{company.phone.first.number}}">
	    					<div class="gouser_button">
	    						<span class="glyphicon glyphicon-phone-alt"></span>
	    					</div>
	    				</a>
		    		</div>
	    		</div>
    		</div>
		</div>
		<div class="container container_small">
			<div class="row">
				
				<div class="info_company">
					<div class="field_title">
						单位简介
					</div>
					<div class="field_content">
						{{company.info|safe}}
					</div>
				</div>
				
				<div class="address">
					<div class="field_title">
						地址
					</div>
					<div class="field_content">
						{{company.address}}
					</div>
				</div>
				
				{% for phone in company.phone.all%}
				<div class="phone">
					<a href="tel:{{phone.number}}">
						<div class="tel col-xs-9">
							{{phone.number}}
						</div>
						<div class="tel_icon col-xs-3">
							<span class="glyphicon glyphicon-earphone"></span>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
	</body>
</html>

benzhu_system/apps/service/templates/service_comment.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	    <title>benzhu_system</title>
	    <script src="/static/web/js/jquery-1.11.1.min.js"></script>
	    <script src="/static/web/js/swipe.js"></script>
	    <link rel="stylesheet" href="/static/web/css/main.css" />
	    <link rel="stylesheet" href="/static/web/css/bootstrap.css">
	    <script>
			$(function() {
				$(".banner_left").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"white"} );
					$(".goback_button").css( {"color":"#FF4A00"} );
				});
				$(".banner_left").bind("touchend", function() {
					$(this).css( {"backgroundColor":"transparent"} );
					$(".goback_button").css( {"color":"white"} );
				});
				$(".banner_right").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"#FD9729"} );
				});
				$(".banner_right").bind("touchend", function() {
					$(this).css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
				$(".input_button").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"transparent", "color":"#FF4A00"} );
				});
				$(".input_button").bind("touchend", function() {
					$(this).css( {"backgroundColor":"#FF4A00", "color":"white"} );
				});
			});	
			$(function(){
				new Swipe(document.getElementById('banner_box'), {
					speed:500,
					auto:3000,
					callback: function(){
						var lis = $(this.element).next("ol").children();
						lis.removeClass("on").eq(this.index).addClass("on"); }
					});
			});
		</script>
	</head>
	<body class="apps_background">
		<div class="container-fluid service_detail">
			<div class="row">
	    		<div class="banner">
	    			<div class="banner_left col-xs-2">
	    				<a href="javascript:history.back()">
	    					<div class="goback_button">
	    						<span class="glyphicon glyphicon-arrow-left"></span>
	    					</div>
	    				</a>
					</div>	
		    		<div class="banner_middle col-xs-8">
		    			<div class="service_name">
		    				{{service.name}}
		    			</div>
		    		</div>
		    		<div class="banner_right col-xs-2">
		    			<a href="tel:{{service.company.phone.first.number}}">
	    					<div class="gouser_button">
	    						<span class="glyphicon glyphicon-phone-alt"></span>
	    					</div>
	    				</a>
		    		</div>
	    		</div>
    		</div>
    	</div>
		<div class="container container_small">
			<div class="row">
				{% load comments %}
				{% get_comment_list for service as comments %}
				<div class="info feedback_form">
					<div class="field_title">
						对{{service.name}}进行评价
					</div>
					{% get_comment_form for service as blog_form %}
					<div class="notice_content">
						<form class="form-horizontal" action="{% comment_form_target %}" method="post" id="cmt_sub_form">
			    			{% csrf_token %}
				            {{ blog_form.object_pk }}
				            {{ blog_form.content_type }}
				            {{ blog_form.timestamp }}
				            {{ blog_form.site }}
				            {{ blog_form.submit_date }}
				            {{ blog_form.security_hash }}
				            <div class="control-group" style="display: none;">
				              <label class="control-label" for="id_name">用户名： </label>
				              <div class="controls">
				                <input readonly="readonly" type="text" id="id_name" class="input-xlarge" name="name" placeholder="请输入您的用户名" value="{{ user.username }}"/>
				              </div>
				            </div>
				            <div class="control-group" style="display: none;">
				              <label class="control-label" for="id_email">E-mail： </label>
				              <div class="controls">
				                <input readonly="readonly" class="input-xlarge" id="id_email" type="email" name="email" placeholder="请输入您的邮箱地址" value="{{ user.email }}"/>
				              </div>
				            </div>
							<textarea id="id_comment" name="comment" class="feedback_textarea" placeholder="请输入你的评价"></textarea>
							<div class="input_star">
								<span >评分：</span>
								<span id="star_1" class="glyphicon glyphicon-star-empty"></span>
								<span id="star_2" class="glyphicon glyphicon-star-empty"></span>
								<span id="star_3" class="glyphicon glyphicon-star-empty"></span>
								<span id="star_4" class="glyphicon glyphicon-star-empty"></span>
								<span id="star_5" class="glyphicon glyphicon-star-empty"></span>
							</div>
							<script>
								$("#star_1").bind("touchstart", function() {
									$("#id_star").val("1");
									$("#star_1").removeClass("glyphicon-star-empty")
									$("#star_1").addClass("glyphicon-star");
									$("#star_2").removeClass("glyphicon-star")
									$("#star_2").addClass("glyphicon-star-empty");
									$("#star_3").removeClass("glyphicon-star")
									$("#star_3").addClass("glyphicon-star-empty");
									$("#star_4").removeClass("glyphicon-star")
									$("#star_4").addClass("glyphicon-star-empty");
									$("#star_5").removeClass("glyphicon-star")
									$("#star_5").addClass("glyphicon-star-empty");
								});
								$("#star_2").bind("touchstart", function() {
									$("#id_star").val("2");
									$("#star_1").removeClass("glyphicon-star-empty")
									$("#star_1").addClass("glyphicon-star");
									$("#star_2").removeClass("glyphicon-star-empty")
									$("#star_2").addClass("glyphicon-star");
									$("#star_3").removeClass("glyphicon-star")
									$("#star_3").addClass("glyphicon-star-empty");
									$("#star_4").removeClass("glyphicon-star")
									$("#star_4").addClass("glyphicon-star-empty");
									$("#star_5").removeClass("glyphicon-star")
									$("#star_5").addClass("glyphicon-star-empty");
								});
								$("#star_3").bind("touchstart", function() {
									$("#id_star").val("3");
									$("#star_1").removeClass("glyphicon-star-empty")
									$("#star_1").addClass("glyphicon-star");
									$("#star_2").removeClass("glyphicon-star-empty")
									$("#star_2").addClass("glyphicon-star");
									$("#star_3").removeClass("glyphicon-star-empty")
									$("#star_3").addClass("glyphicon-star");
									$("#star_4").removeClass("glyphicon-star")
									$("#star_4").addClass("glyphicon-star-empty");
									$("#star_5").removeClass("glyphicon-star")
									$("#star_5").addClass("glyphicon-star-empty");
								});
								$("#star_4").bind("touchstart", function() {
									$("#id_star").val("4");
									$("#star_1").removeClass("glyphicon-star-empty")
									$("#star_1").addClass("glyphicon-star");
									$("#star_2").removeClass("glyphicon-star-empty")
									$("#star_2").addClass("glyphicon-star");
									$("#star_3").removeClass("glyphicon-star-empty")
									$("#star_3").addClass("glyphicon-star");
									$("#star_4").removeClass("glyphicon-star-empty")
									$("#star_4").addClass("glyphicon-star");
									$("#star_5").removeClass("glyphicon-star")
									$("#star_5").addClass("glyphicon-star-empty");
								});
								$("#star_5").bind("touchstart", function() {
									$("#id_star").val("5");
									$("#star_1").removeClass("glyphicon-star-empty")
									$("#star_1").addClass("glyphicon-star");
									$("#star_2").removeClass("glyphicon-star-empty")
									$("#star_2").addClass("glyphicon-star");
									$("#star_3").removeClass("glyphicon-star-empty")
									$("#star_3").addClass("glyphicon-star");
									$("#star_4").removeClass("glyphicon-star-empty")
									$("#star_4").addClass("glyphicon-star");
									$("#star_5").removeClass("glyphicon-star-empty")
									$("#star_5").addClass("glyphicon-star");
								});
							</script>
							<input id="id_star" type="hidden" name="star" value="" class="input_text input_star" placeholder="请输入您的评分" />
							<input type="submit" name="submit" value="提交" class="input_button"/>
						</form>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

benzhu_system/apps/service/templates/service_detail.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	    <title>benzhu_system</title>
	    <script src="/static/web/js/jquery-1.11.1.min.js"></script>
	    <script src="/static/web/js/swipe.js"></script>
	    <link rel="stylesheet" href="/static/web/css/main.css" />
	    <link rel="stylesheet" href="/static/web/css/bootstrap.css">
	    <script>
			$(function() {
				$(".banner_left").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"white"} );
					$(".goback_button").css( {"color":"#FF4A00"} );
				});
				$(".banner_left").bind("touchend", function() {
					$(this).css( {"backgroundColor":"transparent"} );
					$(".goback_button").css( {"color":"white"} );
				});
				$(".banner_right").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"#FD9729"} );
				});
				$(".banner_right").bind("touchend", function() {
					$(this).css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
				$(".phone").bind("touchstart", function() {
					$(this).find(".tel").css( {"backgroundColor":"#D4D7DA"} );
					$(this).find(".tel_icon").css( {"backgroundColor":"#FD9729"} );
				});
				$(".phone").bind("touchend", function() {
					$(this).find(".tel").css( {"backgroundColor":"rgba(94,92,87,0.8)"} );
					$(this).find(".tel_icon").css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
				$(".phone").bind("touchmove", function() {
					$(this).find(".tel").css( {"backgroundColor":"rgba(94,92,87,0.8)"} );
					$(this).find(".tel_icon").css( {"backgroundColor":"rgba(255,74,0,0.9)"} );
				});
				$(".ghost_button2_index").bind("touchstart", function() {
					$(this).css( {"backgroundColor":"transparent", "color":"#FF4A00"} );
				});
				$(".ghost_button2_index").bind("touchend", function() {
					$(this).css( {"backgroundColor":"#FF4A00", "color":"white"} );
				});
			});	
			$(function(){
				new Swipe(document.getElementById('banner_box'), {
					speed:500,
					auto:3000,
					callback: function(){
						var lis = $(this.element).next("ol").children();
						lis.removeClass("on").eq(this.index).addClass("on"); }
					});
			});
		</script>

		<script>
		var set_star = function( selector ) {
			$(selector).each( function() {
				var star = Math.round( parseFloat( $(this).find('.star').val() ) );
				star = (star > 5 || star < 0 ? 5 : star);
				$(this).find('.glyphicon:lt('+ star +')').addClass('glyphicon-star');
				$(this).find('.glyphicon:not(:lt('+ star +'))').addClass('glyphicon-star-empty');
			});				
		}

		$(function(){
			set_star('.comment_star, .field_content');
		});
		</script>


</head>
	<body class="apps_background">
		{% for post in posts %}
		<div class="container-fluid service_detail">
			<div class="row">
	    		<div class="banner">
	    			<div class="banner_left col-xs-2">
	    				<a href="javascript:history.back()">
	    					<div class="goback_button">
	    						<span class="glyphicon glyphicon-arrow-left"></span>
	    					</div>
	    				</a>
					</div>	
		    		<div class="banner_middle col-xs-8">
		    			<div class="service_name">
		    				{{post.name}}
		    			</div>
		    		</div>
		    		<div class="banner_right col-xs-2">
		    			<a href="tel:{{post.company.phone.first.number}}">
	    					<div class="gouser_button">
	    						<span class="glyphicon glyphicon-phone-alt"></span>
	    					</div>
	    				</a>
		    		</div>
	    		</div>
    		</div>
    		<div class="row">
	    		<div id="banner_box" class="box_swipe">
					<ul>
						{% for pictures in gallery %}
						<li>
							<a href="http://{{pictures.links}}">
								<img src="{{MEDIA_URL}}{{ pictures.pic }}" alt="" style="width:100%;" />
							</a>
						</li>
						{% endfor %}
					</ul>
			
					<ol>
						{% for pictures in gallery %}
						<li class=""></li>
						{% endfor %}
					</ol>
				</div>
	    	</div>
		</div>
		<div class="container container_small">
			<div class="row">
				
				<div class="info">
					<div class="field_title">
						服务简介
					</div>
					<div class="field_content">
						{{post.info|safe}}
					</div>
				</div>
				
				<div class="company">
					<div class="field_content">
						<input class="star" type="hidden" value="{{ avg_star }}" />
						<span class="glyphicon"></span>
						<span class="glyphicon"></span>
						<span class="glyphicon"></span>
						<span class="glyphicon"></span>
						<span class="glyphicon"></span>
					</div>
				</div>
				
				<div class="company">
					<div class="field_title">
						服务提供单位
					</div>
					<a href="/company/{{post.company.id}}">
						<div class="field_content row">
							<div class="col-xs-10">
								{{post.company.name}}
							</div>
							<div class="col-xs-2">
								<span class="glyphicon glyphicon-chevron-right"></span>
							</div>
						</div>
					</a>
				</div>
				
				<div class="info2">
					<div class="field_title">
						地址
					</div>
					<div class="field_content">
						{{post.company.address}}
					</div>
				</div>
				

				<div class="address">

					{% load comments %}
					{% get_comment_list for service as comments %}

					<div class="field_title">
						  {% get_comment_count for service as comment_count %}
						  <div class="comments_nav"><a href="comment">评论({{ comment_count }})</a></div>
					</div>

					<div class="field_content">

					  <div class="comments">
						  <a name="blog_comments" id="comments"></a>
						 
						  {% ifequal comment_count 0 %}
							<div class="comments_body">
							  <div class="comment_container">没有评论</div>
							</div>
						  {% else %}
							{% get_comment_list for service as comments %}
							<div class="comments_body">
								{% for comment in comments reversed%}
								<div class="comment_container row">
								  <div class="cmt_user_info col-xs-6"> 
									<span class="comment_name">{{ comment.user_name }}</span>
									
								  </div>
								  <div class="comment_star col-xs-6">
								  	<span class="comment_time">{{ comment.submit_date|date:"Y-m-d"}}</span></br>
								  	<span class="glyphicon glyphicon-star"></span>
								  	<span class="glyphicon glyphicon-star"></span>
								  	<span class="glyphicon glyphicon-star-empty"></span>
								  	<span class="glyphicon glyphicon-star-empty"></span>
								  	<span class="glyphicon glyphicon-star-empty"></span>
								  </div>
								  <div class="comment_content col-xs-12">{{ comment.comment }}</div>
								</div>
								{% endfor %}
								<div class="comment_button">
									<a href="comment"><div class="ghost_button2_index radius_button"><span class="glyphicon glyphicon-pencil"> 我要评论</span></div></a>
								</div>
							</div>
						  {% endifequal %}
					 </div>
						  
					
					</div>
				</div>

				
				{% for phone in post.company.phone.all%}
				<div class="phone">
					<a href="tel:{{phone.number}}">
						<div class="tel col-xs-9">
							{{phone.number}}
						</div>
						<div class="tel_icon col-xs-3">
							<span class="glyphicon glyphicon-earphone"></span>
						</div>
					</a>
				</div>
				{% endfor %}
				
				
			</div>
			
		</div>
		
		{% endfor %}
	</body>
</html>